# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b9c0d03232ee32b667ee46110807e5905fbfd9742254e1b9453bb60df0e62a496d68d5918ab4b720527b28714736d603dc05b5be9142b9a05acb1cc864242fe

test:
  secret_key_base: 7f7e0a10400b15d540a5c54726b4659b098777d43b0cffece3e31694eb40eb30fced7a204cefe2869ea0e2c1bbbceb9fedc70c588d779eefe4fae8aa45a61470

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
